# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pw_hashed',
        ),
    ]
