# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 17:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('courseManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
