# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20161220_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_reg.User'),
        ),
    ]
