# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20161216_1845'),
        ('courses', '0008_auto_20161220_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_reg.User'),
        ),
    ]
