# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_routes', '0002_auto_20161222_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='semi_restful_routes.Product'),
        ),
    ]
